### ISSUE TITLE
Login / Registration

### ISSUE THREAD

**Issue by nicholaswall** [KirubelMoges/CS3330_Spring21#5]
## Overview
Before we can really get started with most of the features of the app, at least a basic set of login features need to be implemented. Eventually it would be ideal to have alternative authentication providers like Google OAuth, but email/username password is good enough to begin. This is going to require work from DB and GUI, and it is a high priority issue.

## Tasks

- [x] Frontend login page with form
- [x] Frontend error handling
- [x] Frontend persist login state - cookies/localStorage/ect.
- [x] Backend login/register routes
- [x] Backend create user table and connect to API
- [x] Backend hashing password/ **No plaintext passwords**
